// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA2zIaxgo_OmnaS1RuNRcb1eSC1d462NY',
    appId: '1:431177158089:web:1b2dccdc3187219af8ac18',
    messagingSenderId: '431177158089',
    projectId: 'ice-cream-pos-4b34e',
    authDomain: 'ice-cream-pos-4b34e.firebaseapp.com',
    storageBucket: 'ice-cream-pos-4b34e.firebasestorage.app',
    measurementId: 'G-X3JK7PDLD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr7p8CyPyNSvw_D3OfpOsCnWfgeyUT_Vo',
    appId: '1:431177158089:android:4cb1458202d12ecbf8ac18',
    messagingSenderId: '431177158089',
    projectId: 'ice-cream-pos-4b34e',
    storageBucket: 'ice-cream-pos-4b34e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQolEbDhc5GMUVoiWLeO3KT3yRexUx2_I',
    appId: '1:431177158089:ios:2f7673e0944a3865f8ac18',
    messagingSenderId: '431177158089',
    projectId: 'ice-cream-pos-4b34e',
    storageBucket: 'ice-cream-pos-4b34e.firebasestorage.app',
    iosBundleId: 'com.example.iceCream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQolEbDhc5GMUVoiWLeO3KT3yRexUx2_I',
    appId: '1:431177158089:ios:2f7673e0944a3865f8ac18',
    messagingSenderId: '431177158089',
    projectId: 'ice-cream-pos-4b34e',
    storageBucket: 'ice-cream-pos-4b34e.firebasestorage.app',
    iosBundleId: 'com.example.iceCream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA2zIaxgo_OmnaS1RuNRcb1eSC1d462NY',
    appId: '1:431177158089:web:72cd526d8bcb8888f8ac18',
    messagingSenderId: '431177158089',
    projectId: 'ice-cream-pos-4b34e',
    authDomain: 'ice-cream-pos-4b34e.firebaseapp.com',
    storageBucket: 'ice-cream-pos-4b34e.firebasestorage.app',
    measurementId: 'G-TDC2TLX76Z',
  );
}
